exclude: (\.git/|\.venv/|build/|static/|dist/)
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: check-yaml
  - id: check-added-large-files
    args: ['--maxkb=2000']
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: '^.+?(\.json|\.po)$'

- repo: https://github.com/PyCQA/flake8
  rev: 7.0.0
  hooks:
  - id: flake8

- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.12.0
  hooks:
  - id: reorder-python-imports

- repo: https://github.com/psf/black
  rev: 24.4.2
  hooks:
  - id: black
