name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pre-commit
        pre-commit install -f --install-hooks

    - name: Lint
      run: pre-commit run -a
